# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"  
  
  config.vm.hostname = "docker-host"
  config.vm.provision "docker"
  config.vm.network "private_network", ip: "192.168.33.110"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

end
